name: Development CI/CD
on:
  push:
    branches:
     - "development"
  
  pull_request:
    branches:
     - "development"

env:
  CI: false
  env_dev: ${{ secrets.ENV_DEV }}

jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
      
      - name: create environment file
        run: |
          touch ./.env && echo "$env_dev" >> ./.env

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build && push web
        id: build-push-web
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: esatya/tayaba-web:dev
          
